"""Static transform generated by icp_calib."""
"""Calibration result: base -> camera_2_link."""
from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description() -> LaunchDescription:
    nodes = [
        Node(
            package="tf2_ros",
            executable="static_transform_publisher",
            output="log",
            arguments=[
                "--frame-id",
                'base',
                "--child-frame-id",
                'realsense2_link',
                "--x",
                "0.0966589330764",
                "--y",
                "0.278370371633",
                "--z",
                "0.498150219851",
                "--qx",
                "0.648514544752",
                "--qy",
                "0.020210850009",
                "--qz",
                "-0.302200195198",
                "--qw",
                "0.698351951962",
            ],
        ),
    ]
    return LaunchDescription(nodes)
