"""Static transform generated by icp_calib."""
"""Calibration result: base -> camera_2_link."""
from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description() -> LaunchDescription:
    nodes = [
        Node(
            package="tf2_ros",
            executable="static_transform_publisher",
            output="log",
            arguments=[
                "--frame-id",
                'base',
                "--child-frame-id",
                'realsense2_link',
                "--x",
                "0.00749670486333",
                "--y",
                "0.287229858805",
                "--z",
                "0.130861926801",
                "--qx",
                "-0.00251415622326",
                "--qy",
                "0.031870280672",
                "--qz",
                "-0.0958859577002",
                "--qw",
                "0.994878810381",
            ],
        ),
    ]
    return LaunchDescription(nodes)
